service: amazops-backend

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  httpApi:
    cors: true
    authorizers:
      jwtAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: !Join ["", ["https://cognito-idp.${self:provider.region}.amazonaws.com/", !Ref UserPool]]
        audience:
          - !Ref UserPoolClient
  environment:
    MASTER_TABLE: master-table-${self:provider.stage}
    FBA_COUNTRIES: fba-countries-${self:provider.stage}
    USER_POOL: default-user-pool-${self:provider.stage}
    USER_POOL_CLIENT: default-user-pool-client-${self:provider.stage}
    SUBSCRIPTION_INDEX: subscription-index

functions:
  createOrder: ${file(serverless/lambda/createOrder.yml)}
  getOrder: ${file(serverless/lambda/getOrder.yml)}
  queryAllOrders: ${file(serverless/lambda/queryAllOrders.yml)}
  updateOrder: ${file(serverless/lambda/updateOrder.yml)}
  deleteOrder: ${file(serverless/lambda/deleteOrder.yml)}
  updateOrderEvents: ${file(serverless/lambda/updateOrderEvents.yml)}
  queryAllOrderEvents: ${file(serverless/lambda/queryAllOrderEvents.yml)}
  scanAllFBACountries: ${file(serverless/lambda/scanAllFBACountries.yml)}
  stripeWebhook: ${file(serverless/lambda/stripeWebhook.yml)}
  querySubscription: ${file(serverless/lambda/querySubscription.yml)}
  getUserMetadata: ${file(serverless/lambda/getUserMetadata.yml)}
  createCustomerPortalSession: ${file(serverless/lambda/createCustomerPortalSession.yml)}

resources:
  - Resources:
      MasterTable: ${file(serverless/dynamodb/masterTable.yml)}
      FBACountriesTable: ${file(serverless/dynamodb/FBACountries.yml)}
      CreateOrderRole: ${file(serverless/iam/createOrderRole.yml)}
      GetOrderRole: ${file(serverless/iam/getOrderRole.yml)}
      QueryAllOrdersRole: ${file(serverless/iam/queryAllOrdersRole.yml)}
      UpdateOrderRole: ${file(serverless/iam/updateOrderRole.yml)}
      DeleteOrderRole: ${file(serverless/iam/deleteOrderRole.yml)}
      UpdateOrderEventsRole: ${file(serverless/iam/updateOrderEventsRole.yml)}
      QueryAllOrderEventsRole: ${file(serverless/iam/queryAllOrderEventsRole.yml)}
      ScanAllFBACountriesRole: ${file(serverless/iam/scanAllFBACountriesRole.yml)}
      StripeWebhookRole: ${file(serverless/iam/stripeWebhookRole.yml)}
      QuerySubscriptionRole: ${file(serverless/iam/querySubscriptionRole.yml)}
      GetUserMetadataRole: ${file(serverless/iam/getUserMetadataRole.yml)}
      CreateCustomerPortalSessionRole: ${file(serverless/iam/createCustomerPortalSessionRole.yml)}
      UserPool: ${file(serverless/cognito/userPool.yml)}
      UserPoolClient: ${file(serverless/cognito/userPoolClient.yml)}
      UserPoolDomain: ${file(serverless/cognito/userPoolDomain.yml)}
